# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 455)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 40, 55, 16))
        self.label.setObjectName("label")
        self.taste = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.taste.setGeometry(QtCore.QRect(110, 200, 113, 22))
        self.taste.setObjectName("taste")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 160, 55, 16))
        self.label_4.setObjectName("label_4")
        self.size = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.size.setGeometry(QtCore.QRect(110, 280, 113, 22))
        self.size.setObjectName("size")
        self.id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id.setGeometry(QtCore.QRect(110, 40, 113, 22))
        self.id.setObjectName("id")
        self.roasting = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.roasting.setGeometry(QtCore.QRect(110, 120, 113, 22))
        self.roasting.setObjectName("roasting")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 80, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 240, 55, 16))
        self.label_6.setObjectName("label_6")
        self.title = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(110, 80, 113, 22))
        self.title.setObjectName("title")
        self.updateBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.updateBtn.setGeometry(QtCore.QRect(130, 340, 93, 28))
        self.updateBtn.setObjectName("updateBtn")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 200, 55, 16))
        self.label_5.setObjectName("label_5")
        self.type = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.type.setGeometry(QtCore.QRect(110, 160, 113, 22))
        self.type.setObjectName("type")
        self.coast = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.coast.setGeometry(QtCore.QRect(110, 240, 113, 22))
        self.coast.setObjectName("coast")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 280, 55, 16))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 415, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "id"))
        self.label_4.setText(_translate("MainWindow", "type"))
        self.label_2.setText(_translate("MainWindow", "title"))
        self.label_6.setText(_translate("MainWindow", "coast"))
        self.updateBtn.setText(_translate("MainWindow", "Применить"))
        self.label_3.setText(_translate("MainWindow", "roasting"))
        self.label_5.setText(_translate("MainWindow", "taste"))
        self.label_7.setText(_translate("MainWindow", "size"))
